# Generated by Django 4.1.4 on 2022-12-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantprofile",
            name="opening_hours",
        ),
    ]
