# Generated by Django 4.1.4 on 2022-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_restaurantprofile_opening_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghour",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Senin"),
                    (1, "Selasa"),
                    (2, "Rabu"),
                    (3, "Kamis"),
                    (4, "Jumat"),
                    (5, "Sabtu"),
                    (6, "Minggu"),
                ],
                unique=True,
            ),
        ),
    ]
